openapi: 3.0.0
info:
  title: Fraud Detection API - Detailed
  version: v013
  description: Detailed API specification for survey response analysis for fraudulent activity detection.
paths:
  /v013:
    post:
      summary: Detailed survey response analysis
      description: Analyzes survey responses to detect fraudulent activity with detailed request and response structure.
      parameters:
        - name: api_key
          in: header
          required: true
          schema:
            type: string
          description: API key for authentication. Include this in the header of your request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                participant_id:
                  type: string
                  description: A unique identifier for the participant for version v013.
                  example: "participant_123"
                question_histories:
                  type: object
                  description: Records the changes made by the participant while answering the survey for version v013. Each key is the id of the question, and the value is the array of changes generated by our Javascript tracker.
                  example: {"Q1": []}
                questions:
                  type: object
                  description: Contains the survey questions for version v013. Each key is the id of the question, and the values are the text of the open-ended survey questions as shown to the participant.
                  example: {"Q1": "How do you feel our software has impacted your daily workflow?"}
                responses:
                  type: object
                  description: Records the participant's final responses to each question for version v013.
                  example: {"Q1": "I really like pineapple on pizza."}
                survey_id:
                  type: string
                  description: A unique identifier for the survey for version v013.
                  example: "survey_456"
              required:
                - participant_id
                - questions
                - responses
                - survey_id
      responses:
        '200':
          description: Analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    description: Indicates if there was an error in processing the request for version v013.
                    example: false
                  flagged:
                    type: boolean
                    description: Indicates the type of fraudulent activity detected for version v013. This example shows an off-topic response detected.
                    example: true
                  num_checks_failed:
                    type: integer
                    description: Number of checks that failed for version v013.
                    example: 1
                  response_groups:
                    type: object
                    description: Dictionary where key corresponds to question_id and value corresponds to the cluster of duplicated responses.
                    example: {"Q1": 1}
                  checks:
                    type: object
                    description: |
                      Dictionary where keys correspond to questions, and every entry is an array of strings, each string representing a failed check. Possible checks include:
                      - "Automated test: Gibberish" - The response is not coherent or grammatical.
                      - "Automated test: Off-topic" - The response does not address or relate to the question.
                      - "Automated test: Low-effort" - The response relates to the question but provides minimal information.
                      - "Automated test: GPT" - The response is flagged as likely generated by a GPT model.
                      - "GPT paste artifacts" - The text is formatted similarly to ChatGPT outputs.
                      - "Response pasted" - The response was pasted or entered programmatically.
                      - "Self-duplicate response" - A similar or identical answer was given to more than one question.
                      - "Cross-duplicate response" - A similar or identical answer as another participant was provided.
                    additionalProperties:
                      type: array
                      items:
                        type: string
                    example: {"Q1": ["Automated test: Off-topic"]}
                  model:
                    type: string
                    description: String specifying the model type.
                    example: "alias-v013"
  /v012:
    post:
      summary: Detailed survey response analysis for v012
      description: Analyzes survey responses to detect fraudulent activity with detailed request and response structure for version v012.
      parameters:
        - name: api_key
          in: header
          required: true
          schema:
            type: string
          description: API key for authentication. Include this in the header of your request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                participant_id:
                  type: string
                  description: A unique identifier for the participant for version v012.
                  example: "participant_123"
                question_histories:
                  type: object
                  description: Records the changes made by the participant while answering the survey for version v012. Each key is the id of the question, and the value is the array of changes generated by our Javascript tracker.
                  example: {"Q1": []}
                questions:
                  type: object
                  description: Contains the survey questions for version v012. Each key is the id of the question, and the values are the text of the open-ended survey questions as shown to the participant.
                  example: {"Q1": "How do you feel our product has impacted your daily workflow?"}
                responses:
                  type: object
                  description: Records the participant's final responses to each question for version v012.
                  example: {"Q1": "I really like pineapple on pizza."}
                survey_id:
                  type: string
                  description: A unique identifier for the survey for version v012.
                  example: "survey_456"
              required:
                - participant_id
                - questions
                - responses
                - survey_id
      responses:
        '200':
          description: Analysis result for v012
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    description: Indicates if there was an error in processing the request for version v012.
                    default: false
                  flagged:
                    type: boolean
                    description: Indicates if any fraudulent activity was detected for version v012. If true, we recommend reviewing the participant's responses for version v012.
                  model:
                    type: string
                    description: String specifying the model type.
                    example: alias-v012
                  num_checks_failed:
                    type: integer
                    description: Number of checks that failed for version v012.
                    example: 1
                  checks:
                    type: object
                    description: |
                      Details of specific checks and their outcomes for version v012. Available options include:
                      - "All responses empty" - The participant didn't answer any question.
                      - "Text chunking" - Some text was generated in a chunk (rather than character-by-character).
                      - "GPT paste artifacts" - Text is formatted in a highly similar way to ChatGPT.
                      - "Self-duplicate response" - The participant gave the same answer to more than one question.
                      - "Cross-duplicate response" - The participant gave the same answer as another participant (excluding simple answers like 'Yes' or 'No').
                      - "Unnatural typing speed" - The participant typed abnormally fast or slow.
                      - "Unnatural pausing" - The participant paused in a way that is common to GPTs but not to humans.
                      - "Automated test: Junk" - Our ML model flags this response as likely junk.
                      - "Automated test: GPT" - Our ML model flags this response as likely generated by a GPT.
                    additionalProperties:
                      type: array
                      items:
                        type: string
                    example: ["Automated test: Junk"]
                  response_groups:
                    type: object
                    description: Dictionary where key corresponds to question_id and value corresponds to the cluster of duplicated responses.
                  warning:
                    type: string
                    description: A message that provides additional context or information about potential issues detected during the request processing for version v012. Only returned if there is a warning.
  /v011:
    post:
      summary: Detailed survey response analysis for v011
      description: Analyzes survey responses to detect fraudulent activity with detailed request and response structure for version v011.
      parameters:
        - name: api_key
          in: header
          required: true
          schema:
            type: string
          description: API key for authentication. Include this in the header of your request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                participant_id:
                  type: string
                  description: A unique identifier for the participant.
                  example: "participant_123"
                question_histories:
                  type: object
                  description: Records the changes made by the participant while answering the survey. Each key is the id of the question, and the value is the array of changes generated by our Javascript tracker.
                  example: {"Q1": []}
                questions:
                  type: object
                  description: Contains the survey questions. Each key is the id of the question, and the values are the text of the open-ended survey questions as shown to the participant.
                  example: {"Q1": "How do you feel our product has impacted your daily workflow?"}
                responses:
                  type: object
                  description: Records the participant's final responses to each question.
                  example: {"Q1": "I really like pineapple on pizza."}
                survey_id:
                  type: string
                  description: A unique identifier for the survey.
                  example: "survey_456"
              required:
                - participant_id
                - questions
                - responses
                - survey_id
      responses:
        '200':
          description: Analysis result for v011
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    description: Indicates if there was an error in processing the request.
                  flagged:
                    type: boolean
                    description: Indicates if any fraudulent activity was detected for version v011. If true, we recommend reviewing the participant's responses.
                  num_checks_failed:
                    type: integer
                    description: Number of checks that failed for version v011.
                    example: 1
                  checks:
                    type: array
                    items:
                      type: string
                    description: Details of specific checks and their outcomes for version v011. Includes various checks like automated tests and response analysis.
                    example: ["Automated test: Junk"]
                  warning:
                    type: string
                    description: A message that provides additional context or information about potential issues detected during the request processing for version v011. Only returned if there is a warning.
